version: '3.8'

services:
  # PostgreSQL Database
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: healthsync-postgres
  #   environment:
  #     POSTGRES_USER: healthsync
  #     POSTGRES_PASSWORD: healthsync_dev
  #     POSTGRES_DB: healthsync
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - healthsync-network

  # Next.js Frontend Application
  # frontend:
  #   build:
  #     context: ./apps/frontend
  #     dockerfile: Dockerfile
  #   container_name: healthsync-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_PUBLIC_API_URL=http://orchestrator:4000
  #   volumes:
  #     - ./apps/frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - orchestrator
  #   networks:
  #     - healthsync-network

  # Node.js Orchestrator Backend
  # orchestrator:
  #   build:
  #     context: ./apps/orchestrator
  #     dockerfile: Dockerfile
  #   container_name: healthsync-orchestrator
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://healthsync:healthsync_dev@postgres:5432/healthsync
  #     - JWT_SECRET=your-secret-key-change-in-production
  #   volumes:
  #     - ./apps/orchestrator:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgres
  #   networks:
  #     - healthsync-network

  # Python FastAPI Client Adapter (Federated Learning)
  # client-adapter:
  #   build:
  #     context: ./services/client-adapter
  #     dockerfile: Dockerfile
  #   container_name: healthsync-client-adapter
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - ORCHESTRATOR_URL=http://orchestrator:4000
  #   volumes:
  #     - ./services/client-adapter:/app
  #   networks:
  #     - healthsync-network

# volumes:
#   postgres-data:

# networks:
#   healthsync-network:
#     driver: bridge
